FROM arm32v6/alpine:3.20@sha256:50f635c8b04d86dde8a02bcd8d667ba287eb8b318c1c0cf547e5a48ddadea1be AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

ENTRYPOINT ["/usr/bin/mygithub"]
CMD ["help"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/mygithub /usr/bin/mygithub
